apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - ../../base

# Point image names at the ECR registry. CD pipeline runs
# `kustomize edit set image <name>=<registry>/<repo>:<sha>` to pin the tag.
# Account 503577850741, region eu-west-1.
images:
  - name: gateway-api
    newName: 503577850741.dkr.ecr.eu-west-1.amazonaws.com/m2cloud-gateway-api
    newTag: latest
  - name: realtime
    newName: 503577850741.dkr.ecr.eu-west-1.amazonaws.com/m2cloud-realtime
    newTag: latest
  - name: worker
    newName: 503577850741.dkr.ecr.eu-west-1.amazonaws.com/m2cloud-worker
    newTag: latest
  - name: web
    newName: 503577850741.dkr.ecr.eu-west-1.amazonaws.com/m2cloud-web
    newTag: latest
